
  - name: disabling the old module
    ansible.builtin.command: dnf module disable redis -y

  - name: enabling the old module
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: installing redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: changing the port
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: changing the protected mode option
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected mode'
      line: protected-mode no

  - name: enable and start redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
  