  - name: app setup
    include_role:
      name: common
      tasks_from: app-setup

  - name: nodejs
    include_role:
      name: common
      tasks_from: nodejs
    
  - name: copying repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-mongosh
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: check products
    ansible.builtin.command: mongosh --host mongodb.dpractice.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
  
  - name: print catalogue_output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.dpractice.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: system-setup
    include_role:
      name: common
      tasks_from: system-setup