- name: stop service
  tags: 
  - deployment
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped
  
- name: remove code
  ansible.builtin.file:
    path: /app
    state: absent

- name: unzipping
  ansible.builtin.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip"
    dest: /app
    remote_src: yes

- name: install dependencies
  ansible.builtin.npm:
    path: /app

- name: restart
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted