  - name: catalogue service
    ansible.builtin.template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service

  - name: reloading
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and restart
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes